version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitsperity-bitspark_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/bitsperitybtc/bitspark:sha-32593df@sha256:a8cc4e3fe797d9ccc80301caa44aeb953ee19c736d4887b445002ecfc9cc54e1
    restart: on-failure
    stop_grace_period: 1m
    init: true
